import React from 'react';
import { RecommendationStack } from '@/lib/recommendation';
import { Button } from '@/components/ui/button';
import { Download, Copy } from 'lucide-react';
import { toast } from 'sonner';
interface RecommendationExportsProps {
  stack: RecommendationStack | null;
}
function generateMarkdown(stack: RecommendationStack): string {
  let md = `# Your AI Stack Recommendation: ${stack.title}\n\n`;
  md += `**Summary:** ${stack.summary}\n\n`;
  md += `**Estimated Total Monthly Cost:** $${stack.estimatedTotalMonthlyCost}\n\n`;
  md += `## Recommended Tools\n\n`;
  stack.tools.forEach(tool => {
    md += `### ${tool.toolName} (${tool.role})\n\n`;
    md += `*   **Rationale:** ${tool.rationale}\n`;
    md += `*   **Estimated Cost:** $${tool.monthlyCost}/month\n`;
    md += `*   **Confidence:** ${tool.confidence}%\n`;
    md += `*   **Documentation:** [${tool.docsUrl}](${tool.docsUrl})\n\n`;
    md += `#### Quick Start Plan\n\n`;
    md += `1.  ${tool.starterPlan.step1}\n`;
    md += `2.  ${tool.starterPlan.step2}\n`;
    md += `3.  ${tool.starterPlan.step3}\n\n`;
    if (tool.quickstartSnippet) {
      md += `\`\`\`${tool.quickstartSnippet.language}\n`;
      md += `${tool.quickstartSnippet.code}\n`;
      md += `\`\`\`\n\n`;
    }
    md += '---\n\n';
  });
  md += `Generated by StackSculptor.`;
  return md;
}
export function RecommendationExports({ stack }: RecommendationExportsProps) {
  if (!stack) return null;
  const handleDownload = () => {
    const markdown = generateMarkdown(stack);
    const blob = new Blob([markdown], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'stack-recommendation.md';
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    toast.success('Markdown guide downloaded!');
  };
  const handleCopy = () => {
    const markdown = generateMarkdown(stack);
    navigator.clipboard.writeText(markdown);
    toast.success('Copied starter guide to clipboard!');
  };
  return (
    <div className="flex items-center gap-4">
      <Button onClick={handleDownload}>
        <Download className="mr-2 h-4 w-4" />
        Download Guide (.md)
      </Button>
      <Button variant="outline" onClick={handleCopy}>
        <Copy className="mr-2 h-4 w-4" />
        Copy to Clipboard
      </Button>
    </div>
  );
}